version: 2

sources:
  - name: raw_local_bike
    database: cas-final-local-bike
    schema: raw_local_bike

    tables:
      - name: brands
      - name: categories
      - name: customers
      - name: order_items
      - name: orders
      - name: products
      - name: staffs
      - name: stocks
      - name: stores